# Generated by Django 4.1.3 on 2022-12-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_doctor_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization_details_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergancy_contact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='iin_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_num',
            field=models.IntegerField(null=True),
        ),
    ]
